[build]
publish = "public"
command = "hugo --gc --minify" 

[build.environment]
TZ = 'Australia/Melbourne'

[context.production.environment]
HUGO_VERSION = "0.164.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.164.0"

# Fix the CORS issue between articles.foletta.org and blog.foletta.net
[[headers]]
  for = "/fontawesome/webfonts/fa-brands-400.woff2" 
  [headers.values]
    access-control-allow-origin = "https://articles.foletta.org"
